In [1]:
import pandas as pd
import numpy as np

In [2]:
file = '../dataframes/hogares.csv'
df_h = pd.read_csv(file, encoding='latin')
df_h.head()

Unnamed: 0  adqui_pc  cel_hogar  celular  chofer  cocinero  compu_uso  \
0           0        -1         -1        2      -1        -1          1   
1           1        -1         -1        2      -1        -1          1   
2           2        -1         -1        1      -1        -1          1   
3           3        -1         -1        1      -1        -1          1   
4           4        -1         -1        2      -1        -1          2   

   compu_uso2  conex_int1  conex_int2  ...   tiempo_pc  tot_hom  tot_integ  \
0          -1           2           1  ...           2        3          4   
1          -1           2           1  ...           2        3          4   
2          -1           2           1  ...           2        1          2   
3          -1           2           1  ...           3        2          6   
4           2          -1          -1  ...          -1        2          4   

   tot_muj  trabaja_do  tv_analogi  tv_digital  tv_paga  videojuego  year  
0        1          -1           1           1        2           2  2014  
1        1          -1           2           1        1           1  2014  
2        1          -1           1           2        1           2  2014  
3        4          -1           1           2        1           2  2014  
4        2          -1           1           2        2           2  2014  

[5 rows x 59 columns]

In [3]:
file = '../dataframes/viviendas.csv'
df_v = pd.read_csv(file, encoding='latin')
df_v.head()

Unnamed: 0   ageb  aire_acond  ais_otro  ais_pared  ais_techos  ais_ventan  \
0           0  029-0           2        -1         -1          -1          -1   
1           1  029-0           2        -1         -1          -1          -1   
2           2  029-0           2        -1         -1          -1          -1   
3           3  029-0           2        -1         -1          -1          -1   
4           4  030-3           2        -1         -1          -1          -1   

   anio_panel  anio_res  antiguedad  ...   tot_hog  tot_resid  tv_paga  \
0          -1        -1          30  ...         1          4       -1   
1          -1        -1          26  ...         1          4       -1   
2          -1        -1          23  ...         1          2       -1   
3          -1        -1          10  ...         1          6       -1   
4          -1        -1          -1  ...         1          4       -1   

   ubica_geo   upm  uso_compar  valor_viv  vend_hered  viv_usada  year  
0   10010001   710           2         -1          -1         -1  2014  
1   10010001   710           2         -1          -1         -1  2014  
2   10010001   710           2         -1          -1          2  2014  
3   10010001   710           2         -1          -1         -1  2014  
4   10010001  1450           2         -1          -1          1  2014  

[5 rows x 135 columns]

In [4]:
df_h_copy = df_h.copy()

In [5]:
df_v_copy = df_v.copy()

## Merge

In [222]:
df_inner = pd.merge(left=df_v_copy, right=df_h_copy, how='inner', on='folioviv')
df_inner.head()

Unnamed: 0_x   ageb  aire_acond  ais_otro  ais_pared  ais_techos  \
0             0  029-0           2        -1         -1          -1   
1             0  029-0           2        -1         -1          -1   
2            19  029-0           2        -1         -1          -1   
3            19  029-0           2        -1         -1          -1   
4             1  029-0           2        -1         -1          -1   

   ais_ventan  anio_panel  anio_res  antiguedad   ...    tiempo_pc  tot_hom  \
0          -1          -1        -1          30   ...            2        3   
1          -1          -1        -1          30   ...           -1        2   
2          -1          -1        -1          42   ...            2        3   
3          -1          -1        -1          42   ...           -1        2   
4          -1          -1        -1          26   ...            2        3   

   tot_integ  tot_muj  trabaja_do  tv_analogi  tv_digital  tv_paga_y  \
0          4        1          -1           1           1          2   
1          6        4          -1           1           2          2   
2          4        1          -1           1           1          2   
3          6        4          -1           1           2          2   
4          4        1          -1           2           1          1   

   videojuego  year_y  
0           2    2014  
1          -1    2015  
2           2    2014  
3          -1    2015  
4           1    2014  

[5 rows x 193 columns]

In [223]:
df_inner.shape

(254928, 193)

In [224]:
df_h.shape

(220871, 59)

In [225]:
df_v.shape

(217147, 135)

In [226]:
df_inner.columns[df_inner.isnull().any()].tolist()

[]

In [227]:
for line in df_inner.columns:
    print(line, ' : ', df_inner[line].unique(), '\n')

Unnamed: 0_x  :  [    0    19     1 ..., 58592 58593 58594] 

ageb  :  ['029-0' '030-3' '034-1' ..., '252-0' '144-7' '256-9'] 

aire_acond  :  [2 1] 

ais_otro  :  [-1  2  9  1] 

ais_pared  :  [-1  2  9  1] 

ais_techos  :  [-1  2  9  1] 

ais_ventan  :  [-1  2  9  1] 

anio_panel  :  [  -1 2015 2014 2010 2006 2007 2002 2001 2012 2005 2008 2016 2013 2009 2011
 2004 2017] 

anio_res  :  [-1  1  6  0 10  2  8 11  3 12 32  7 30  5 19  4 23  9 14 13 15 22 21 60 18
 28 16 17 20 25 40 50 35 29 44 47 27 39 26 36 45 61 42 37] 

antiguedad  :  [30 42 26 20 23 16 10 -1 40 33 35 36 50 34 43 45 78  3 60 28 70 39 32 25 15
 56 80 99 69 47 46 41 14 24 12 44 19 55 27  9  7 22 29  4 31 13  8  2  5  6
 37 38  1 18 11 21 17 48 90 65 52  0 64 54 53 84 95 72 74 49 51 75 63 58 73
 62 68 67 89 86 57 59 66 83 92 81 77 98 71 85 79 94 76 87 97 88 82 61 91 93
 96] 

auto_pick  :  [-1  1  2] 

bano_comp  :  [ 2  3  4  1  0  5 -1  6  8  7  9] 

bano_excus  :  [ 0  1  2  3 -1  9  8  4  6  5] 

bano_regad  :  [ 0  

### Merge `compu_uso` y `computador`

In [228]:
df_inner['compu_uso'].value_counts()

-1    116606
 2     86214
 1     52108
Name: compu_uso, dtype: int64

In [229]:
df_inner['computador'].value_counts()

-1    138322
 2     74550
 1     42056
Name: computador, dtype: int64

In [230]:
i = 0
list_computador = []
for row_a, row_b in zip(df_inner['compu_uso'].tolist(), df_inner['computador'].tolist()):
    if(row_a == -1) & (row_b == 1):
        list_computador.append(1)

    elif(row_a == -1) & (row_b == 2):
        list_computador.append(2)
        
    elif(row_a == 1) & (row_b == -1):
        list_computador.append(1)

    elif(row_a == 2) & (row_b == -1):
        list_computador.append(2)
        
    else:
        list_computador.append(-1)
        
    i+=1
    
i

254928

In [231]:
np.unique(list_computador)

array([-1,  1,  2])

In [232]:
len(list_computador)

254928

In [233]:
df_inner['computador'] = list_computador
df_inner['computador'].value_counts()

 2    160754
 1     94158
-1        16
Name: computador, dtype: int64

### Merge `conex_inte` y `internet`

In [234]:
df_inner['conex_inte'].value_counts()

-1    116606
 2     82173
 1     56014
 9       135
Name: conex_inte, dtype: int64

In [235]:
df_inner['internet'].value_counts()

-1    138322
 2     58698
 1     57908
Name: internet, dtype: int64

In [236]:
i = 0
list_internet = []
for row_a, row_b in zip(df_inner['conex_inte'].tolist(), df_inner['internet'].tolist()):
    if(row_a == -1) & (row_b == 1):
        list_internet.append(1)

    elif(row_a == -1) & (row_b == 2):
        list_internet.append(2)
        
    elif(row_a == 1) & (row_b == -1):
        list_internet.append(1)

    elif(row_a == 2) & (row_b == -1):
        list_internet.append(2)
        
    else:
        list_internet.append(-1)
        
    i+=1
    
i

254928

In [237]:
np.unique(list_internet)

array([-1,  1,  2])

In [238]:
len(list_internet)

254928

In [239]:
df_inner['internet'] = list_internet
df_inner['internet'].value_counts()

 2    140864
 1    113913
-1       151
Name: internet, dtype: int64

### Merge `celular_x` y `celular_x`

In [240]:
df_inner['celular_x'].value_counts()

-1    138322
 1     71312
 2     45294
Name: celular_x, dtype: int64

In [241]:
df_inner['celular_y'].value_counts()

-1    116606
 1     98625
 2     39695
 9         2
Name: celular_y, dtype: int64

In [242]:
i = 0
list_celular = []
for row_a, row_b in zip(df_inner['celular_x'].tolist(), df_inner['celular_y'].tolist()):
    if(row_a == -1) & (row_b == 1):
        list_celular.append(1)

    elif(row_a == -1) & (row_b == 2):
        list_celular.append(2)
        
    elif(row_a == 1) & (row_b == -1):
        list_celular.append(1)

    elif(row_a == 2) & (row_b == -1):
        list_celular.append(2)
        
    else:
        list_celular.append(-1)
        
    i+=1
    
i

254928

In [243]:
np.unique(list_celular)

array([-1,  1,  2])

In [244]:
len(list_celular)

254928

In [245]:
df_inner['celular'] = list_celular
df_inner['celular'].value_counts()

 1    169924
 2     84986
-1        18
Name: celular, dtype: int64

### Merge `tel_fijo_x` y `tel_fijo_y`

In [246]:
df_inner['tel_fijo_x'].value_counts()

-1    138322
 2     70657
 1     45949
Name: tel_fijo_x, dtype: int64

In [247]:
df_inner['tel_fijo_y'].value_counts()

-1    116606
 2     88660
 1     49661
 9         1
Name: tel_fijo_y, dtype: int64

In [248]:
i = 0
list_tel_fijo = []
for row_a, row_b in zip(df_inner['tel_fijo_x'].tolist(), df_inner['tel_fijo_y'].tolist()):
    if(row_a == -1) & (row_b == 1):
        list_tel_fijo.append(1)

    elif(row_a == -1) & (row_b == 2):
        list_tel_fijo.append(2)
        
    elif(row_a == 1) & (row_b == -1):
        list_tel_fijo.append(1)

    elif(row_a == 2) & (row_b == -1):
        list_tel_fijo.append(2)
        
    else:
        list_tel_fijo.append(-1)
        
    i+=1
    
i

254928

In [249]:
np.unique(list_tel_fijo)

array([-1,  1,  2])

In [250]:
len(list_tel_fijo)

254928

In [251]:
df_inner['tel_fijo'] = list_tel_fijo
df_inner['tel_fijo'].value_counts()

 2    159306
 1     95605
-1        17
Name: tel_fijo, dtype: int64

### Merge `tv_paga_x` y `tv_paga_y`

In [252]:
df_inner['tv_paga_x'].value_counts()

-1    138322
 1     81279
 2     35327
Name: tv_paga_x, dtype: int64

In [253]:
df_inner['tv_paga_y'].value_counts()

-1    116606
 2     74750
 1     63495
 9        77
Name: tv_paga_y, dtype: int64

In [254]:
i = 0
list_tv_paga = []
for row_a, row_b in zip(df_inner['tv_paga_x'].tolist(), df_inner['tv_paga_y'].tolist()):
    if(row_a == -1) & (row_b == 1):
        list_tv_paga.append(1)

    elif(row_a == -1) & (row_b == 2):
        list_tv_paga.append(2)
        
    elif(row_a == 1) & (row_b == -1):
        list_tv_paga.append(1)

    elif(row_a == 2) & (row_b == -1):
        list_tv_paga.append(2)
        
    else:
        list_tv_paga.append(-1)
        
    i+=1
    
i

254928

In [255]:
np.unique(list_tv_paga)

array([-1,  1,  2])

In [256]:
len(list_tv_paga)

254928

In [257]:
df_inner['tv_paga'] = list_tv_paga
df_inner['tv_paga'].value_counts()

 1    144762
 2    110073
-1        93
Name: tv_paga, dtype: int64

### Merge `calentador` y `calent_sol` o `calent_gas`

In [258]:
df_inner['calentador'].value_counts()

-1    116606
 2     77820
 1     60502
Name: calentador, dtype: int64

In [259]:
df_inner['calent_sol'].value_counts()

-1    138322
 2    110638
 1      5968
Name: calent_sol, dtype: int64

In [260]:
df_inner['calent_gas'].value_counts()

-1    138322
 2     69449
 1     47157
Name: calent_gas, dtype: int64

In [261]:
i = 0
list_calentador = []

for row_a, row_b, row_c in zip(df_inner['calentador'].tolist(), df_inner['calent_sol'].tolist(), df_inner['calent_gas'].tolist()):
    if(row_a == -1) & ((row_b == 1) | (row_b == 1)):
        list_calentador.append(1)

    elif(row_a == -1) & ((row_b == 2) | (row_b == 2)):
        list_calentador.append(2)
        
    elif(row_a == 1) & ((row_b == -1) | (row_b == -1)):
        list_calentador.append(1)

    elif(row_a == 2) & ((row_b == -1) | (row_b == -1)):
        list_calentador.append(2)
        
    else:
        list_calentador.append(-1)
        
    i+=1
    
i

254928

In [262]:
np.unique(list_calentador)

array([1, 2])

In [263]:
len(list_calentador)

254928

In [264]:
df_inner['calentador'] = list_calentador
df_inner['calentador'].value_counts()

2    188458
1     66470
Name: calentador, dtype: int64

### Merge `tot_resid` y `tot_integ`

In [265]:
df_inner['tot_resid'].value_counts().head()

-1    57523
 4    44536
 3    37819
 2    32790
 5    31715
Name: tot_resid, dtype: int64

In [266]:
df_inner['tot_integ'].value_counts().head()

4    58486
3    50397
2    44600
5    39955
1    25631
Name: tot_integ, dtype: int64

In [267]:
i = 0
list_tot_integ = []

for row_a, row_b in zip(df_inner['tot_resid'].tolist(), df_inner['tot_integ'].tolist()):
    if(row_a == -1) & (row_b > 0):
        list_tot_integ.append(row_b)
    else:
        list_tot_integ.append(row_b) 
        
    i+=1
    
i

254928

In [268]:
np.unique(list_tot_integ)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 22, 24])

In [269]:
len(list_tot_integ)

254928

In [270]:
df_inner['tot_integ'] = list_tot_integ
df_inner['tot_integ'].value_counts()

4     58486
3     50397
2     44600
5     39955
1     25631
6     18564
7      8720
8      4147
9      2113
10     1155
11      569
12      254
13      144
14       75
15       48
16       29
17       17
20        9
19        7
18        6
22        1
24        1
Name: tot_integ, dtype: int64

In [294]:
import re
ubica_geo = df_inner.ubica_geo.astype('str')
ubica_geo.head()

0    10010001
1    10010001
2    10010001
3    10010001
4    10010001
Name: ubica_geo, dtype: object

In [332]:
for row, index in zip(ubica_geo, ubica_geo.index):
    if len(row) == 8:
        ubica_geo[index] = '0' + row
ubica_geo[0]        

'010010001'

In [337]:
ubica_geo[0][:2]

'01'

In [338]:
ubica_geo[0][2:5]

'001'

In [339]:
ubica_geo[0][5:]

'0001'

In [368]:
ubica_geo[1][:2]

'01'

In [384]:
list_CVE_ENT = []
list_CVE_MUN = []
list_CVE_LOC = []

for index in ubica_geo.index:
    list_CVE_ENT.append(ubica_geo[index][:2])
    list_CVE_MUN.append(ubica_geo[index][2:5])
    list_CVE_LOC.append(ubica_geo[index][5:])

In [388]:
df_inner['CVE_ENT'] = list_CVE_ENT
df_inner['CVE_ENT'].unique()

array(['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11',
       '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '30', '31', '32'], dtype=object)

In [390]:
df_inner['CVE_MUN'] = list_CVE_MUN
df_inner['CVE_MUN'].unique()

array(['001', '003', '005', '006', '007', '011', '004', '002', '009',
       '010', '008', '018', '025', '030', '035', '020', '024', '027',
       '028', '037', '038', '017', '033', '036', '013', '078', '089',
       '101', '019', '061', '065', '074', '075', '094', '097', '106',
       '029', '031', '046', '081', '087', '099', '102', '108', '111',
       '015', '052', '076', '012', '014', '021', '022', '023', '034',
       '041', '054', '059', '067', '070', '092', '098', '103', '112',
       '114', '032', '040', '045', '060', '062', '051', '016', '039',
       '042', '050', '057', '058', '066', '043', '055', '071', '077',
       '079', '048', '069', '082', '084', '063', '044', '073', '083',
       '068', '120', '053', '085', '093', '104', '109', '121', '122',
       '091', '118', '064', '088', '119', '124', '107', '072', '100',
       '110', '026', '049', '184', '385', '390', '397', '399', '515',
       '090', '157', '185', '227', '293', '327', '375', '384', '401',
       '409', '441',

In [391]:
df_inner['CVE_LOC'] = list_CVE_LOC
df_inner['CVE_LOC'].unique()

array(['0001', '1025', '0023', '0041', '0245', '0030', '0367', '0026',
       '0109', '0482', '0040', '0144', '2381', '0992', '0988', '0047',
       '0014', '0034', '0248', '0266', '0424', '0472', '0391', '0464',
       '0028', '0261', '0370', '0393', '0024', '0008', '0107', '0133',
       '0187', '0381', '1599', '1781', '1561', '2183', '0340', '1883',
       '0089', '0118', '0211', '1273', '1303', '2086', '2317', '2575',
       '2008', '3134', '1721', '2396', '1685', '3174', '0883', '1625',
       '0873', '0054', '0753', '0280', '0003', '0247', '0952', '1435',
       '0684', '0035', '0967', '0456', '1374', '0985', '1500', '0720',
       '0738', '0939', '1164', '0004', '0007', '0087', '0101', '0199',
       '0045', '0432', '0010', '0104', '0081', '3217', '0094', '0066',
       '0027', '0043', '0050', '0569', '0568', '0333', '0838', '0761',
       '0673', '1002', '0179', '0313', '0164', '0171', '0077', '0076',
       '0124', '0236', '0355', '0680', '0130', '0382', '0153', '0638',
      

### Drop all columns down 50% na threshold

In [271]:
n = df_inner.columns.values.tolist()
m = round(df_inner.shape[0]*.50)
l = []
for i in n:
    if df_inner[i].value_counts().get(-1) != None:
        if m < df_inner[i].value_counts().get(-1):
            l.append(i)
            df_inner.drop(labels=i, axis=1, inplace=True)

In [272]:
l

['ais_otro',
 'ais_pared',
 'ais_techos',
 'ais_ventan',
 'anio_panel',
 'anio_res',
 'auto_pick',
 'calent_gas',
 'calent_sol',
 'celular_x',
 'comun1',
 'comun10',
 'comun11',
 'comun12',
 'comun13',
 'comun14',
 'comun15',
 'comun16',
 'comun17',
 'comun2',
 'comun3',
 'comun4',
 'comun5',
 'comun6',
 'comun7',
 'comun8',
 'comun9',
 'condominio',
 'dispos_ne',
 'dispos_nh1',
 'dispos_nh2',
 'dispos_no1',
 'dispos_no2',
 'elevador',
 'estaciona',
 'estufa_chi',
 'factor',
 'facul_ne',
 'facul_nh1',
 'facul_nh2',
 'facul_no1',
 'facul_no2',
 'familiar',
 'financia_1',
 'financia_2',
 'financia_3',
 'financia_4',
 'financia_5',
 'financia_6',
 'financia_7',
 'financia_8',
 'hog_dueno2',
 'mes_res',
 'num_dueno2',
 'pago_renta',
 'panel_ne',
 'pot_panel',
 'potencia',
 'rega_elect',
 'ren_estufa',
 'ren_horno',
 'ren_lavad',
 'ren_planch',
 'ren_refri',
 'ren_tv',
 'tel_fijo_x',
 'tipo_finan',
 'tv_paga_x',
 'valor_viv',
 'vend_hered',
 'viv_usada',
 'adqui_pc',
 'cel_hogar',
 'chofer'

In [393]:
df_inner.shape

(254928, 60)

In [282]:
l_2 = ['Unnamed: 0_x', 'Unnamed: 0_y', 'ageb', 'est_dis', 'factor_viv', 'folioviv', 'hog_dueno1', 'num_dueno1', 'upm', 'celular_y', 'compu_uso', 'conex_inte', 'factor_hog', 'foliohog', 'tel_fijo_y', 'tv_paga_y', 'const_neg', 'cocina_dor', 'tipo_adqui', 'const_neg', 'cocina_dor', 'tipo_adqui', 'celular_y', 'compu_uso', 'conex_inte', 'num_trab_d', 'radio', 'tel_fijo_y', 'tv_analogi', 'tv_digital', 'tv_paga_y', 'escrituras', 'tot_resid', ubica_geo]

In [279]:
df_inner['año'] = df_inner.year_x

In [280]:
df_inner.drop(labels=['year_x', 'year_y'], axis=1, inplace=True)

In [283]:
df_inner.drop(labels=l_2, axis=1, inplace=True)
df_inner.shape

ValueError: labels ['Unnamed: 0_x' 'Unnamed: 0_y' 'ageb' 'est_dis' 'factor_viv' 'folioviv'
 'hog_dueno1' 'num_dueno1' 'upm' 'celular_y' 'compu_uso' 'conex_inte'
 'factor_hog' 'foliohog' 'tel_fijo_y' 'tv_paga_y' 'const_neg' 'cocina_dor'
 'tipo_adqui' 'const_neg' 'cocina_dor' 'tipo_adqui' 'celular_y' 'compu_uso'
 'conex_inte' 'num_trab_d' 'radio' 'tel_fijo_y' 'tv_analogi' 'tv_digital'
 'tv_paga_y'] not contained in axis

In [287]:
for line in df_inner.columns:
    print(line, ' : ', df_inner[line].value_counts(), '\n')

aire_acond  :  2    207467
1     47461
Name: aire_acond, dtype: int64 

antiguedad  :  -1     64173
 20    16408
 10    15677
 30    14071
 15    13152
 25     8366
 40     7913
 8      7485
 5      7393
 12     6169
 7      5764
 6      5693
 3      4890
 4      4863
 35     4777
 9      4398
 2      4282
 50     4004
 18     3912
 14     3550
 13     3318
 1      3235
 16     3098
 17     2824
 11     2699
 22     2552
 28     1969
 23     1942
 45     1765
 24     1683
       ...  
 63       43
 66       38
 67       31
 74       25
 77       23
 85       20
 61       18
 72       17
 78       16
 73       15
 69       15
 76       14
 71       13
 95       12
 86        9
 87        8
 84        8
 98        8
 81        8
 79        6
 82        5
 83        5
 88        5
 89        4
 97        3
 92        2
 94        2
 93        1
 96        1
 91        1
Name: antiguedad, Length: 101, dtype: int64 

bano_comp  :   1    136654
 0     68404
 2     33084
-1      8900
 3      

In [394]:
df_inner.shape

(254928, 60)

In [395]:
df_inner.to_csv('enh.csv')

# OPCIONAL

### Fill `antiguedad`

In [146]:
list_antiguedad = df_inner.antiguedad[df_inner.antiguedad > -1].mean()
antiguedad_mean = round(list_antiguedad)
antiguedad_mean

20

In [147]:
df_inner.antiguedad.replace({-1: antiguedad_mean}, inplace=True)
df_inner.antiguedad = df_inner.antiguedad.astype('int64')
df_inner.antiguedad.value_counts().head()

20    80581
10    15677
30    14071
15    13152
25     8366
Name: antiguedad, dtype: int64

### Fill `bano_comp`

In [148]:
list_bano_comp = df_inner.bano_comp[df_inner.bano_comp > -1].mean()
bano_comp_mean = round(list_bano_comp)
bano_comp_mean

1

In [149]:
df_inner.bano_comp.replace({-1: bano_comp_mean}, inplace=True)
df_inner.bano_comp = df_inner.bano_comp.astype('int64')
df_inner.bano_comp.value_counts().head()

1    145554
0     68404
2     33084
3      6096
4      1342
Name: bano_comp, dtype: int64

### Fill `bano_excus`

In [150]:
list_bano_excus = df_inner.bano_excus[df_inner.bano_excus > -1].mean()
bano_excus_mean = round(list_bano_excus)
bano_excus_mean

0

In [151]:
df_inner.bano_excus.replace({-1: bano_excus_mean}, inplace=True)
df_inner.bano_excus = df_inner.bano_excus.astype('int64')
df_inner.bano_excus.value_counts().head()

0    158347
1     91457
2      4524
3       312
9       165
Name: bano_excus, dtype: int64

### Fill `bano_regad`

In [152]:
list_bano_regad = df_inner.bano_regad[df_inner.bano_regad > -1].mean()
bano_regad_mean = round(list_bano_regad)
bano_regad_mean

0

In [153]:
df_inner.bano_regad.replace({-1: bano_regad_mean}, inplace=True)
df_inner.bano_regad = df_inner.bano_regad.astype('int64')
df_inner.bano_regad.value_counts().head()

0    248010
1      6556
9       181
2       122
8        39
Name: bano_regad, dtype: int64

### Fill `focos_ahor`

In [152]:
list_bano_regad = df_inner.bano_regad[df_inner.bano_regad > -1].mean()
bano_regad_mean = round(list_bano_regad)
bano_regad_mean

0

In [153]:
df_inner.bano_regad.replace({-1: bano_regad_mean}, inplace=True)
df_inner.bano_regad = df_inner.bano_regad.astype('int64')
df_inner.bano_regad.value_counts().head()

0    248010
1      6556
9       181
2       122
8        39
Name: bano_regad, dtype: int64