In [14]:
import pandas as pd
import numpy as np

# 2014

## Vivienda

In [15]:
file = '../data/2014/bd_envipe2014/bd_envipe2014/TVivienda.csv'
df_v14 = pd.read_csv(file, encoding='latin')
df_v14['year'] = 2014
df_v14.head()

Unnamed: 0  CONTROL  VIV_SEL  ENT  MUN  LOC  AREAM  RESUL_V  AP1_1  AP1_2  \
0           0   100001        1    1    1    1   14.0        2      1      2   
1           1   100001        2    1    1    1   14.0        2      2      2   
2           2   100001        3    1    1    1   14.0        2      2      2   
3           3   100001        4    1    1    1   14.0        1      2      2   
4           4   100001        5    1    1    1   14.0        2      2      2   

   AP2_1  AP2_2  AP2_3  NAP2_3  FAC_VIV DOM  EST  UPM  FAC_VIV_AM  year  
0      2      1    NaN       1      189   U    5    1       190.0  2014  
1      3      1    NaN       1      189   U    5    1       190.0  2014  
2      7      1    NaN       1      189   U    5    1       190.0  2014  
3      5      1    NaN       1      189   U    5    1       190.0  2014  
4      6      1    NaN       1      189   U    5    1       190.0  2014

In [16]:
df_v14.shape

(85181, 20)

In [17]:
df_v14['ID_VIVIENDA'] = df_v14.CONTROL + df_v14.VIV_SEL

## Victimización 1

In [18]:
file = '../data/2014/bd_envipe2014/bd_envipe2014/TMod_Vic.csv'
df_s14 = pd.read_csv(file, encoding='latin')
df_s14['year'] = 2014
df_s14.head()

Unnamed: 0  CONTROL  VIV_SEL  HOGAR  ND_TIPO  TD_TIPO  BPCOD  R_SEL  \
0           0   140142        5      1        1        1      2      1   
1           1   140049        5      1        1        1      4      1   
2           2   140141        2      1        1        1      2      3   
3           3   140060        2      1        1        1      8      5   
4           4   100012        1      1        2        2      4      1   

   AREAM_OCU RESUL_H  ...   BP6_1  BP6_2  BP6_3  BP7_1  FAC_DEL  DOM  EST  \
0       14.0       A  ...     NaN    NaN    NaN    NaN      178    U    5   
1       14.0       A  ...     NaN    NaN    NaN    NaN      202    U    6   
2       14.0       A  ...     NaN    NaN    NaN    NaN      170    U    4   
3       14.0       A  ...     NaN    NaN    NaN    NaN     1225    U    5   
4       14.0       A  ...     NaN    NaN    NaN    NaN      147    U    4   

   UPM  FAC_DEL_AM  year  
0  107       178.0  2014  
1   45       202.0  2014  
2  106       169.0  2014  
3   52      1218.0  2014  
4    7       146.0  2014  

[5 rows x 123 columns]

In [19]:
df_s14.shape

(43478, 123)

In [20]:
df_s14['ID_VIVIENDA'] = df_s14.CONTROL + df_s14.VIV_SEL

## DICCIONARIO Vivienda - Victimización 1

In [21]:
df_v14.groupby(['ID_VIVIENDA', 'ENT', 'MUN']).size()

ID_VIVIENDA  ENT  MUN
100002       1    1      1
100003       1    1      1
100004       1    1      1
100005       1    1      1
100006       1    1      2
100007       1    1      1
100008       1    1      1
100009       1    1      2
100010       1    1      3
100011       1    1      3
100012       1    1      4
100013       1    1      3
100014       1    1      3
100015       1    1      3
100016       1    1      4
100017       1    1      5
100018       1    1      5
100019       1    1      3
100020       1    1      3
100021       1    1      2
100022       1    1      1
100024       1    1      1
100025       1    1      1
100026       1    1      2
100027       1    1      2
100028       1    1      2
100029       1    1      1
140002       1    1      1
140003       1    1      2
140004       1    1      2
                        ..
3260052      32   35     2
                  38     1
                  39     1
                  42     1
                  55     1
326005

In [22]:
grouped = pd.DataFrame(df_v14.groupby(['ID_VIVIENDA', 'ENT', 'MUN']).size())
grouped.drop([0], axis=1, inplace=True)
grouped.head()

Empty DataFrame
Columns: []
Index: [(100002, 1, 1), (100003, 1, 1), (100004, 1, 1), (100005, 1, 1), (100006, 1, 1)]

In [23]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['ID_VIVIENDA', 'ENT', 'MUN'], dtype='object')

In [24]:
grouped.head()

ID_VIVIENDA  ENT  MUN
0       100002    1    1
1       100003    1    1
2       100004    1    1
3       100005    1    1
4       100006    1    1

In [25]:
dict_grouped = grouped.to_dict(orient='split')
dict_grouped.keys()

dict_keys(['index', 'columns', 'data'])

In [26]:
dict_grouped.pop('index')
dict_grouped.pop('columns')

['ID_VIVIENDA', 'ENT', 'MUN']

In [27]:
dict_grouped['data'][0]

[100002, 1, 1]

In [28]:
dict_grouped['data'][0][0]

100002

In [29]:
array_grouped = grouped.ID_VIVIENDA.unique()
array_grouped

array([ 100002,  100003,  100004, ..., 3260057, 3260058, 3260059])

In [30]:
dict_ID_VIVIENDA_ENT = {}

for line in dict_grouped['data']:
    #print(line[0], ':', line[1])
    dict_ID_VIVIENDA_ENT[line[0]] = line[1]

In [31]:
dict_ID_VIVIENDA_MUN = {}

for line in dict_grouped['data']:
    #print(line[0], ':', line[1])
    dict_ID_VIVIENDA_MUN[line[0]] = line[2]

In [32]:
df_s14['CVE_ENT'] = df_s14['ID_VIVIENDA'].map(dict_ID_VIVIENDA_ENT)

In [33]:
df_s14.CVE_ENT.unique()

array([ 1, 32, 19, 21,  6, 24, 14,  2,  3, 25, 20, 31, 26, 30, 10, 16,  7,
       27,  4, 15, 22, 23,  5, 11,  8, 28,  9, 29, 17, 13, 12, 18])

In [34]:
df_s14['CVE_MUN'] = df_s14['ID_VIVIENDA'].map(dict_ID_VIVIENDA_MUN)

In [35]:
df_s14.CVE_MUN.unique()

array([  5,   1,   7,  11,   9,  10,  57,  48, 114,  35,  53,  44,   8,
       108, 124,   4,   2,   3,  18, 570,  50, 156,  30,  43, 204,  39,
         6,  37,  16,  13,  15,  17,  25,  24,  20,  38,  28,  36,  33,
        32,  27,  14,  23,  98, 121, 118, 106, 101,  97, 100,  89,  61,
       112,  74, 113, 116, 111,  99, 107, 102, 105,  51,  19,  40,  81,
        78,  80,  75,  65,  93,  76, 103,  66,  45,  62,  52, 515,  22,
       513,  46, 110, 104, 122,  12,  70,  58,  26, 109,  29, 120,  91,
        84, 213,  82,  34,  67,  64,  92,  87, 119, 177, 559,  42,  77,
        69,  31,  54,  73,  55,  59,  79,  56, 409,  41, 142, 174, 140,
       505, 208,  60, 193, 545, 202, 194,  85,  68,  49,  95,  88,  21,
       385, 544, 215, 507, 554, 533, 565, 210, 546, 307, 483, 525, 390,
       399, 115, 452, 519, 157, 508, 564, 160, 439, 531,  83, 466, 324,
       340, 350, 375, 168, 199, 189, 207, 217, 138, 183, 197, 178, 152,
       125, 188, 136, 150, 149, 211,  96,  47,  63,  71, 206, 12

In [36]:
df_s14.shape

(43478, 126)

In [37]:
df_s14.to_csv('../dataframes/victimizacion_2014.csv')

# 2015

## Vivienda

In [38]:
file = '../data/2015/TVivienda.csv'
df_v15 = pd.read_csv(file, encoding='latin')
df_v15['year'] = 2015
df_v15.head()

Unnamed: 0     ID_VIV     UPM  VIV_SEL  ENT  MUN  AREAM  RESUL_V  AP1_1  \
0           0  100006.01  100006        1    1    1   14.0        2      1   
1           1  100006.02  100006        2    1    1   14.0        1      1   
2           2  100006.03  100006        3    1    1   14.0        1      1   
3           3  100006.04  100006        4    1    1   14.0        1      1   
4           4  100006.05  100006        5    1    1   14.0        2      1   

   AP1_2  AP2_1  AP2_2  AP2_3  NAP2_3  FAC_VIV  EST_DIS  UPM_DIS DOMINIO  \
0      2      3      1    NaN       1      174        5        1       U   
1      2      4      1    NaN       1      174        5        1       U   
2      2      2      1    NaN       1      174        5        1       U   
3      2      2      1    NaN       1      174        5        1       U   
4      1      3      2    3.0       1      174        5        1       U   

   FAC_VIV_AM  year  
0         173  2015  
1         173  2015  
2         173  2015  
3         173  2015  
4         173  2015

In [39]:
df_v15.shape

(85729, 20)

In [40]:
df_v15['ID_VIVIENDA'] = df_v15.UPM + df_v15.VIV_SEL

## Victimización 1

In [41]:
file = '../data/2015/TMod_Vic.csv'
df_s15 = pd.read_csv(file, encoding='latin')
df_s15['year'] = 2015
df_s15.head()

Unnamed: 0                 ID_DEL     UPM  VIV_SEL  HOGAR  ND_TIPO  \
0           0  0100155.01.01.02.08.1  100155        1      1        1   
1           1  0100462.01.01.02.08.1  100462        1      1        1   
2           2  0100467.04.01.02.02.1  100467        4      1        1   
3           3  0102317.19.01.01.02.1  102317       19      1        1   
4           4  0100738.02.01.02.02.1  100738        2      1        1   

   TD_TIPO  BPCOD  R_SEL  AREAM_OCU  ...  BP6_2  BP6_3  BP7_1  FAC_DEL  \
0        1      8      2       14.0  ...    NaN    NaN    NaN      627   
1        1      8      2       14.0  ...    NaN    NaN    NaN      378   
2        1      2      2       14.0  ...    NaN    NaN    NaN      180   
3        1      2      1       14.0  ...    NaN    NaN    NaN      152   
4        1      2      2       14.0  ...    NaN    NaN    NaN      189   

   EST_DIS  UPM_DIS  DOMINIO  ESTRATO  FAC_DEL_AM  year  
0        5       21        U        3         624  2015  
1        5       64        U        3         376  2015  
2        5       66        U        3         181  2015  
3        2      275        C        3           0  2015  
4        5       92        U        3         189  2015  

[5 rows x 125 columns]

In [42]:
df_s15.shape

(44699, 125)

In [43]:
df_s15['ID_VIVIENDA'] = df_s15.UPM + df_s15.VIV_SEL

## DICCIONARIO Vivienda - Victimización 1

In [44]:
df_v15.groupby(['ID_VIVIENDA', 'ENT', 'MUN']).size()

ID_VIVIENDA  ENT  MUN
100007       1    1      1
100008       1    1      1
100009       1    1      2
100010       1    1      2
100011       1    1      3
100012       1    1      2
100013       1    1      2
100015       1    1      1
100019       1    1      1
100020       1    1      1
100021       1    1      1
100022       1    1      1
100023       1    1      2
100024       1    1      1
100025       1    1      1
100026       1    1      1
100027       1    1      1
100036       1    1      1
100037       1    1      1
100038       1    1      1
100039       1    1      1
100040       1    1      1
100041       1    1      1
100042       1    1      1
100043       1    1      1
100044       1    1      1
100045       1    1      1
100053       1    1      1
100054       1    1      1
100056       1    1      1
                        ..
3260748      32   55     2
3260749      32   55     2
3260750      32   55     1
3260751      32   55     2
3260752      32   55     2
326075

In [45]:
grouped = pd.DataFrame(df_v15.groupby(['ID_VIVIENDA', 'ENT', 'MUN']).size())
grouped.drop([0], axis=1, inplace=True)
grouped.head()

Empty DataFrame
Columns: []
Index: [(100007, 1, 1), (100008, 1, 1), (100009, 1, 1), (100010, 1, 1), (100011, 1, 1)]

In [46]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['ID_VIVIENDA', 'ENT', 'MUN'], dtype='object')

In [47]:
grouped.head()

ID_VIVIENDA  ENT  MUN
0       100007    1    1
1       100008    1    1
2       100009    1    1
3       100010    1    1
4       100011    1    1

In [48]:
dict_grouped = grouped.to_dict(orient='split')
dict_grouped.keys()

dict_keys(['index', 'columns', 'data'])

In [49]:
dict_grouped.pop('index')
dict_grouped.pop('columns')

['ID_VIVIENDA', 'ENT', 'MUN']

In [50]:
dict_grouped['data'][0]

[100007, 1, 1]

In [51]:
dict_grouped['data'][0][0]

100007

In [52]:
array_grouped = grouped.ID_VIVIENDA.unique()
array_grouped

array([ 100007,  100008,  100009, ..., 3260810, 3260811, 3260812])

In [53]:
dict_ID_VIVIENDA_ENT = {}

for line in dict_grouped['data']:
    #print(line[0], ':', line[1])
    dict_ID_VIVIENDA_ENT[line[0]] = line[1]

In [54]:
dict_ID_VIVIENDA_MUN = {}

for line in dict_grouped['data']:
    #print(line[0], ':', line[1])
    dict_ID_VIVIENDA_MUN[line[0]] = line[2]

In [55]:
df_s15['CVE_ENT'] = df_s15['ID_VIVIENDA'].map(dict_ID_VIVIENDA_ENT)

In [56]:
df_s15.CVE_ENT.unique()

array([ 1, 32, 16, 11,  6,  2,  3, 25, 31, 10, 26, 18, 12, 14, 30, 20, 17,
       19,  4,  7, 27,  5, 22, 23, 21,  8, 29,  9, 15, 13, 28, 24])

In [57]:
df_s15['CVE_MUN'] = df_s15['ID_VIVIENDA'].map(dict_ID_VIVIENDA_MUN)

In [58]:
df_s15.CVE_MUN.unique()

array([  1,   7,   5,  11,  35,  24,  34,   6,   9,  20,   2,  10,  56,
         4,   3,  18,   8,  98,  58,  55,  17,  53,  39,  12,  16,  67,
        75,  42,  28,  41,  52, 204,  50,  23,  14,  30,  22,  27,  25,
        38,  32,  33,  36,  37,  26,  97, 105,  15,  46,  47,  89, 101,
        19,  21,  29,  31,  40,  85, 103,  44,  51,  48, 111,  54,  57,
       102,  61, 108,  65, 114,  74,  70,  86,  76,  78, 112,  93,  81,
        87,  79,  92,  96,  94,  99, 100, 107, 106, 109, 116,  45, 350,
        13,  62, 104, 122,  60, 390, 234, 399, 202,  43, 121, 397,  77,
       385, 190, 141,  59, 317,  69,  66,  73, 110, 414,  64,  84,  82,
        63,  83, 120,  71,  72, 124,  68, 113, 134,  91, 194, 119, 188,
        88, 128, 118, 193, 424, 160,  49,  95, 295, 259, 515, 207, 418,
       533, 293, 349, 551, 565, 298, 546, 375, 570, 135, 334, 409, 115,
       142, 157, 184, 185, 198, 200, 215, 525, 278, 439, 324, 327, 333,
       384, 401, 419,  90, 431, 441, 450, 454, 469, 485, 494, 49

In [59]:
df_s15.shape

(44699, 128)

In [60]:
df_s15.to_csv('../dataframes/victimizacion_2015.csv')

# 2016

## Vivienda

In [61]:
file = '../data/2016/tvivienda_envipe2016/conjunto_de_datos/tvivienda_envipe2016.csv'
df_v16 = pd.read_csv(file, encoding='latin')
df_v16['year'] = 2016
df_v16.head()

ID_VIV     UPM  VIV_SEL  ENT  MUN AREAM  RESULT_V  AP1_1  AP1_2  AP2_1  \
0  100006.01  100006        1    1    1  14\r         2      1      2      7   
1  100006.02  100006        2    1    1  14\r         2      1      2      2   
2  100006.03  100006        3    1    1  14\r         2      3      2      8   
3  100006.04  100006        4    1    1  14\r         1      1      2      2   
4  100006.05  100006        5    1    1  14\r         2      1      2      3   

   AP2_2 AP2_3  NAP2_3  FAC_VIV FAC_VIV_AM DOMINIO  EST_DIS  UPM_DIS  year  
0      1    \r       1      168   000168\r     U\r        2        1  2016  
1      1    \r       1      168   000168\r     U\r        2        1  2016  
2      1    \r       1      168   000168\r     U\r        2        1  2016  
3      2  02\r       2      168   000168\r     U\r        2        1  2016  
4      1    \r       1      168   000168\r     U\r        2        1  2016

In [62]:
df_v16.shape

(84140, 19)

In [63]:
df_v16['ID_VIVIENDA'] = df_v16.UPM + df_v16.VIV_SEL

## Victimización 1

In [64]:
file = '../data/2016/tmod_vic_envipe2016/conjunto_de_datos/tmod_vic_envipe2016.csv'
df_s16 = pd.read_csv(file, encoding='latin')
df_s16['year'] = 2016
df_s16.head()

ID_VIV           ID_HOG              ID_PER                   ID_DEL  \
0  101318.05  0101318.05.01\r  0101318.05.01.03\r  0101318.05.01.03.03.1\r   
1  101989.02  0101989.02.01\r  0101989.02.01.02\r  0101989.02.01.02.02.1\r   
2  100777.01  0100777.01.02\r  0100777.01.02.01\r  0100777.01.02.01.02.2\r   
3  101318.03  0101318.03.01\r  0101318.03.01.01\r  0101318.03.01.01.04.1\r   
4  100457.03  0100457.03.01\r  0100457.03.01.03\r  0100457.03.01.03.02.3\r   

      UPM  VIV_SEL  HOGAR  ND_TIPO  TD_TIPO  BPCOD  ...   BP6_2 BP6_3 BP7_1  \
0  101318        5      1        1        1      3  ...      \r    \r    \r   
1  101989        2      1        1        1      2  ...      \r    \r    \r   
2  100777        1      2        2        2      2  ...      \r    \r    \r   
3  101318        3      1        1        1      4  ...      \r    \r    \r   
4  100457        3      1        3        3      2  ...      \r    \r    \r   

   FAC_DEL  FAC_DEL_AM  DOMINIO  ESTRATO  EST_DIS UPM_DIS  year  
0      206    000206\r      U\r        4        3     176  2016  
1      286    000286\r      U\r        2        1     256  2016  
2      195    000195\r      U\r        2        1      99  2016  
3      206    000206\r      U\r        4        3     176  2016  
4      202    000202\r      U\r        2        1      62  2016  

[5 rows x 128 columns]

In [65]:
df_s16.shape

(40026, 128)

In [66]:
df_s16['ID_VIVIENDA'] = df_s16.UPM + df_s16.VIV_SEL

## DICCIONARIO Vivienda - Victimización 1

In [67]:
df_v16.groupby(['ID_VIVIENDA', 'ENT', 'MUN']).size()

ID_VIVIENDA  ENT  MUN
100007       1    1      1
100008       1    1      1
100009       1    1      2
100010       1    1      1
100011       1    1      2
100012       1    1      1
100013       1    1      2
100015       1    1      1
100023       1    1      1
100024       1    1      1
100025       1    1      1
100026       1    1      2
100027       1    1      1
100028       1    1      1
100029       1    1      1
100030       1    1      1
100032       1    1      1
100034       1    1      1
100035       1    1      1
100036       1    1      1
100041       1    1      1
100042       1    1      1
100043       1    1      1
100044       1    1      1
100045       1    1      1
100078       1    1      1
100079       1    1      1
100080       1    1      2
100081       1    1      1
100082       1    1      1
                        ..
3260796      32   37     1
3260797      32   35     1
                  37     1
3260798      32   35     1
                  37     1
326079

In [68]:
grouped = pd.DataFrame(df_v16.groupby(['ID_VIVIENDA', 'ENT', 'MUN']).size())
grouped.drop([0], axis=1, inplace=True)
grouped.head()

Empty DataFrame
Columns: []
Index: [(100007, 1, 1), (100008, 1, 1), (100009, 1, 1), (100010, 1, 1), (100011, 1, 1)]

In [69]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['ID_VIVIENDA', 'ENT', 'MUN'], dtype='object')

In [70]:
grouped.head()

ID_VIVIENDA  ENT  MUN
0       100007    1    1
1       100008    1    1
2       100009    1    1
3       100010    1    1
4       100011    1    1

In [71]:
dict_grouped = grouped.to_dict(orient='split')
dict_grouped.keys()

dict_keys(['index', 'columns', 'data'])

In [72]:
dict_grouped.pop('index')
dict_grouped.pop('columns')

['ID_VIVIENDA', 'ENT', 'MUN']

In [73]:
dict_grouped['data'][0]

[100007, 1, 1]

In [74]:
dict_grouped['data'][0][0]

100007

In [75]:
array_grouped = grouped.ID_VIVIENDA.unique()
array_grouped

array([ 100007,  100008,  100009, ..., 3260810, 3260811, 3260812])

In [76]:
dict_ID_VIVIENDA_ENT = {}

for line in dict_grouped['data']:
    #print(line[0], ':', line[1])
    dict_ID_VIVIENDA_ENT[line[0]] = line[1]

In [77]:
dict_ID_VIVIENDA_MUN = {}

for line in dict_grouped['data']:
    #print(line[0], ':', line[1])
    dict_ID_VIVIENDA_MUN[line[0]] = line[2]

In [78]:
df_s16['CVE_ENT'] = df_s16['ID_VIVIENDA'].map(dict_ID_VIVIENDA_ENT)

In [79]:
df_s16.CVE_ENT.unique()

array([ 1, 14, 12, 32, 24, 19,  2, 25,  3, 18, 31, 26,  6,  5, 21, 23, 29,
        4, 27, 15, 28, 10,  7, 20,  8, 17, 30,  9, 22, 13, 11, 16])

In [80]:
df_s16['CVE_MUN'] = df_s16['ID_VIVIENDA'].map(dict_ID_VIVIENDA_MUN)

In [81]:
df_s16.CVE_MUN.unique()

array([  1,   5,  11,   7,  64,   6,  59,  34,  25,  10,   2,  18,   9,
         4,  17,  50,  55,   3,  12, 101,  30,  28, 114,   8,  14,  39,
        13,  26,  35,  36,  46,  32,  20,  22,  24,  27,  49,  31,  33,
        37,  15,  89, 106,  61, 154,  19,  99,  78,  75, 298,  21,  23,
        29,  83,  71,  40,  57,  41,  85,  47,  51,  52,  66,  65,  67,
        70,  74,  76,  96,  79,  80,  82,  86,  87, 102,  93,  94,  97,
        98, 120, 134, 108, 103, 105, 107, 109, 112, 116,  48,  60,  16,
       121, 104,  58,  81, 124, 179,  69, 122, 413, 115, 170,  43, 189,
       385,  53,  38, 193,  44,  42, 333,  45,  72,  54,  68,  56,  62,
       129,  84,  63,  73,  77, 140, 293, 117, 119,  91, 100, 141,  92,
       118, 110, 111, 113, 131, 184, 202, 485,  88, 186, 207, 198, 397,
       375, 520, 139, 533, 431, 409, 157, 188, 135, 390, 553, 546, 161,
       399, 427, 515, 265, 470, 166, 190, 278, 197, 208, 248, 283, 378,
       295, 309, 315, 317, 467, 401, 324, 327, 334, 346, 384, 43

In [82]:
df_s16.shape

(40026, 131)

In [83]:
df_s16.to_csv('../dataframes/victimizacion_2016.csv')

# 2017

## Vivienda

In [84]:
file = '../data/2017/tvivienda_envipe2017/conjunto_de_datos/tvivienda.csv'
df_v17 = pd.read_csv(file, encoding='latin')
df_v17['year'] = 2017
df_v17.head()

ID_VIV     UPM  VIV_SEL AREAM  CVE_ENT           NOM_ENT  CVE_MUN  \
0  100008.01  100008        1  14\r        1  Aguascalientes\r        1   
1  100008.02  100008        2  14\r        1  Aguascalientes\r        1   
2  100008.04  100008        4  14\r        1  Aguascalientes\r        1   
3  100008.05  100008        5  14\r        1  Aguascalientes\r        1   
4  100022.01  100022        1  14\r        1  Aguascalientes\r        1   

            NOM_MUN  RESULT_V  AP1_1  ...   AP2_1  AP2_2  AP2_3 NAP2_3  \
0  Aguascalientes\r         2      1  ...       4      1     \r      1   
1  Aguascalientes\r         2      1  ...       3      1     \r      1   
2  Aguascalientes\r         2      1  ...       2      1     \r      1   
3  Aguascalientes\r         1      2  ...       3      1     \r      1   
4  Aguascalientes\r         1      1  ...       3      1     \r      1   

   FAC_VIV  FAC_VIV_AM DOMINIO EST_DIS  UPM_DIS  year  
0      204    000204\r     U\r       3        1  2017  
1      204    000204\r     U\r       3        1  2017  
2      204    000204\r     U\r       3        1  2017  
3      204    000204\r     U\r       3        1  2017  
4      198    000198\r     U\r       2        2  2017  

[5 rows x 21 columns]

In [85]:
df_v17.shape

(90618, 21)

In [86]:
df_v17['ID_VIVIENDA'] = df_v17.UPM + df_v17.VIV_SEL

## Victimización 1

In [87]:
file = '../data/2017/tmod_vic_envipe2017/conjunto_de_datos/tmod_vic.csv'
df_s17 = pd.read_csv(file, encoding='latin')
df_s17['year'] = 2017
df_s17.head()

ID_VIV           ID_HOG              ID_PER                 ID_DEL  \
0   100172.02  0100172.02.01\r  0100172.02.01.02\r  0100172.02.01.02.09\r   
1   100931.01  0100931.01.01\r  0100931.01.01.01\r  0100931.01.01.01.03\r   
2   160114.20  0160114.20.01\r  0160114.20.01.01\r  0160114.20.01.01.02\r   
3   100208.04  0100208.04.01\r  0100208.04.01.01\r  0100208.04.01.01.03\r   
4  1409568.04  1409568.04.01\r  1409568.04.01.01\r  1409568.04.01.01.02\r   

       UPM  VIV_SEL  HOGAR  ND_TIPO  TD_TIPO  BPCOD  ...   BP6_2 BP6_3  BP7_1  \
0   100172        2      1        1        1      9  ...      \r    \r     \r   
1   100931        1      1        1        1      3  ...      \r    \r     \r   
2   160114       20      1        4        4      2  ...      \r    \r     \r   
3   100208        4      1        1        2      3  ...      \r    \r     \r   
4  1409568        4      1        1        1      2  ...      \r    \r     \r   

   FAC_DEL FAC_DEL_AM  DOMINIO  ESTRATO  EST_DIS  UPM_DIS  year  
0      364   000364\r      U\r        3        2       11  2017  
1      182   000182\r      U\r        3        2      111  2017  
2      211   000211\r      R\r        2       11      295  2017  
3      147   000147\r      U\r        3        2       15  2017  
4     1026   001026\r      U\r        4      233     6238  2017  

[5 rows x 133 columns]

In [88]:
df_s17.shape

(44630, 133)

In [89]:
df_s17['ID_VIVIENDA'] = df_s17.UPM + df_s17.VIV_SEL

## DICCIONARIO Vivienda - Victimización 1

In [90]:
df_v17.groupby(['ID_VIVIENDA', 'CVE_ENT', 'CVE_MUN']).size()

ID_VIVIENDA  CVE_ENT  CVE_MUN
100009       1        1          1
100010       1        1          1
100012       1        1          1
100013       1        1          1
100023       1        1          1
100024       1        1          1
100025       1        1          1
100027       1        1          1
100060       1        1          1
100061       1        1          1
100062       1        1          1
100063       1        1          1
100064       1        1          1
100080       1        1          1
100081       1        1          1
100082       1        1          1
100084       1        1          1
100091       1        1          1
100092       1        1          1
100093       1        1          1
100094       1        1          1
100095       1        1          1
100102       1        1          1
100103       1        1          1
100104       1        1          2
100106       1        1          3
100107       1        1          2
100108       1        1  

In [91]:
grouped = pd.DataFrame(df_v17.groupby(['ID_VIVIENDA', 'CVE_ENT', 'CVE_MUN']).size())
grouped.drop([0], axis=1, inplace=True)
grouped.head()

Empty DataFrame
Columns: []
Index: [(100009, 1, 1), (100010, 1, 1), (100012, 1, 1), (100013, 1, 1), (100023, 1, 1)]

In [92]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['ID_VIVIENDA', 'CVE_ENT', 'CVE_MUN'], dtype='object')

In [93]:
grouped.head()

ID_VIVIENDA  CVE_ENT  CVE_MUN
0       100009        1        1
1       100010        1        1
2       100012        1        1
3       100013        1        1
4       100023        1        1

In [94]:
dict_grouped = grouped.to_dict(orient='split')
dict_grouped.keys()

dict_keys(['index', 'columns', 'data'])

In [95]:
dict_grouped.pop('index')
dict_grouped.pop('columns')

['ID_VIVIENDA', 'CVE_ENT', 'CVE_MUN']

In [96]:
dict_grouped['data'][0]

[100009, 1, 1]

In [97]:
dict_grouped['data'][0][0]

100009

In [98]:
array_grouped = grouped.ID_VIVIENDA.unique()
array_grouped

array([ 100009,  100010,  100012, ..., 3260819, 3260820, 3260821])

In [99]:
dict_ID_VIVIENDA_ENT = {}

for line in dict_grouped['data']:
    #print(line[0], ':', line[1])
    dict_ID_VIVIENDA_ENT[line[0]] = line[1]

In [100]:
dict_ID_VIVIENDA_MUN = {}

for line in dict_grouped['data']:
    #print(line[0], ':', line[1])
    dict_ID_VIVIENDA_MUN[line[0]] = line[2]

In [101]:
df_s17['CVE_ENT'] = df_s17['ID_VIVIENDA'].map(dict_ID_VIVIENDA_ENT)

In [102]:
df_s17.CVE_ENT.unique()

array([ 1, 14, 32, 22, 28, 11, 24,  8, 20,  2,  3, 25,  6,  9, 10, 26, 12,
       19,  4, 31, 23,  7, 27,  5, 16, 18, 15, 29, 30, 13, 21, 17])

In [103]:
df_s17['CVE_MUN'] = df_s17['ID_VIVIENDA'].map(dict_ID_VIVIENDA_MUN)

In [104]:
df_s17.CVE_MUN.unique()

array([  1, 120,   5,  11,  34,  17,  14,  35,   7,   9,  56,  18,   2,
        10,  37,   3,   4,   6,  28,  49,  85,  15,  39,  30,   8,  21,
        12,  26,  50,  41,  19,  32,  33,  31,  20,  23,  24,  25,  22,
        97,  27,  42,  13,  46,  38, 108, 101,  53, 106,  59,  57,  83,
        99, 107,  29,  40,  65,  47,  48,  51,  52,  61,  68,  67,  69,
        74,  71,  75,  86,  76,  78,  79,  81,  80,  82,  87,  89, 102,
        93,  96, 103,  92, 105, 109, 112, 115,  16,  36,  45,  60, 169,
       117, 124,  58,  54, 104, 186,  77,  70, 122,  94, 208, 234, 141,
       114, 188,  44,  55,  91, 293, 113,  73, 118,  66,  62,  63,  64,
        84, 174,  98, 119, 295, 125, 121, 132, 100, 143, 137, 199,  43,
       194, 110, 111,  88,  95, 157, 160, 515, 140, 385, 441, 557, 184,
       399, 150, 359, 153, 349, 413, 390, 310, 367, 491, 551, 324, 397,
       330, 409, 247, 134, 144, 131, 167, 278, 198, 185, 190, 201, 207,
       226, 237, 248, 253, 309, 318, 334, 401, 439, 344, 375, 35

In [105]:
df_s17.shape

(44630, 136)

In [106]:
df_s17.to_csv('../dataframes/victimizacion_2017.csv')