In [1]:
import pandas as pd
import numpy as np

# 2014

## Vivienda

In [2]:
file = '../data/2014/bd_envipe2014/bd_envipe2014/TVivienda.csv'
df_v14 = pd.read_csv(file, encoding='latin')
df_v14['year'] = 2014
df_v14.head()

Unnamed: 0  CONTROL  VIV_SEL  ENT  MUN  LOC  AREAM  RESUL_V  AP1_1  AP1_2  \
0           0   100001        1    1    1    1   14.0        2      1      2   
1           1   100001        2    1    1    1   14.0        2      2      2   
2           2   100001        3    1    1    1   14.0        2      2      2   
3           3   100001        4    1    1    1   14.0        1      2      2   
4           4   100001        5    1    1    1   14.0        2      2      2   

   AP2_1  AP2_2  AP2_3  NAP2_3  FAC_VIV DOM  EST  UPM  FAC_VIV_AM  year  
0      2      1    NaN       1      189   U    5    1       190.0  2014  
1      3      1    NaN       1      189   U    5    1       190.0  2014  
2      7      1    NaN       1      189   U    5    1       190.0  2014  
3      5      1    NaN       1      189   U    5    1       190.0  2014  
4      6      1    NaN       1      189   U    5    1       190.0  2014

In [3]:
df_v14.shape

(85181, 20)

In [4]:
df_v14['ID_VIVIENDA'] = df_v14.CONTROL + df_v14.VIV_SEL

## Victimización 1

In [5]:
file = '../data/2014/bd_envipe2014/bd_envipe2014/Tper_Vic2.csv'
df_s14 = pd.read_csv(file, encoding='latin')
df_s14['year'] = 2014
df_s14.head()

Unnamed: 0  CONTROL  VIV_SEL  HOGAR RESUL_H  R_SEL  AREAM  AP6_1_1  \
0           0   100001        1      1       B      1   14.0        2   
1           1   100001        2      1       B      2   14.0        2   
2           2   100001        3      1       B      1   14.0        1   
3           3   100001        4      1       A      1   14.0        2   
4           4   100001        5      1       B      3   14.0        1   

   AP6_1_2  AP6_2  ...   AP7_3_15  AP7_4_15  FAC_HOG  FAC_ELE  DOM  EST  UPM  \
0      NaN      2  ...          2       NaN      191      382    U    5    1   
1      NaN      2  ...          2       NaN      191      382    U    5    1   
2      1.0      1  ...          2       NaN      191      764    U    5    1   
3      NaN      1  ...          2       NaN      191      764    U    5    1   
4      1.0      2  ...          2       NaN      191      573    U    5    1   

   FAC_HOG_AM  FAC_ELE_AM  year  
0       192.0       384.0  2014  
1       192.0       384.0  2014  
2       192.0       768.0  2014  
3       192.0       768.0  2014  
4       192.0       576.0  2014  

[5 rows x 130 columns]

In [6]:
df_s14.shape

(84629, 130)

In [7]:
df_s14['ID_VIVIENDA'] = df_s14.CONTROL + df_s14.VIV_SEL

## DICCIONARIO Vivienda - Victimización 1

In [8]:
df_v14.groupby(['ID_VIVIENDA', 'ENT', 'MUN']).size()

ID_VIVIENDA  ENT  MUN
100002       1    1      1
100003       1    1      1
100004       1    1      1
100005       1    1      1
100006       1    1      2
100007       1    1      1
100008       1    1      1
100009       1    1      2
100010       1    1      3
100011       1    1      3
100012       1    1      4
100013       1    1      3
100014       1    1      3
100015       1    1      3
100016       1    1      4
100017       1    1      5
100018       1    1      5
100019       1    1      3
100020       1    1      3
100021       1    1      2
100022       1    1      1
100024       1    1      1
100025       1    1      1
100026       1    1      2
100027       1    1      2
100028       1    1      2
100029       1    1      1
140002       1    1      1
140003       1    1      2
140004       1    1      2
                        ..
3260052      32   35     2
                  38     1
                  39     1
                  42     1
                  55     1
326005

In [9]:
grouped = pd.DataFrame(df_v14.groupby(['ID_VIVIENDA', 'ENT', 'MUN']).size())
grouped.drop([0], axis=1, inplace=True)
grouped.head()

Empty DataFrame
Columns: []
Index: [(100002, 1, 1), (100003, 1, 1), (100004, 1, 1), (100005, 1, 1), (100006, 1, 1)]

In [10]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['ID_VIVIENDA', 'ENT', 'MUN'], dtype='object')

In [11]:
grouped.head()

ID_VIVIENDA  ENT  MUN
0       100002    1    1
1       100003    1    1
2       100004    1    1
3       100005    1    1
4       100006    1    1

In [12]:
dict_grouped = grouped.to_dict(orient='split')
dict_grouped.keys()

dict_keys(['index', 'columns', 'data'])

In [13]:
dict_grouped.pop('index')
dict_grouped.pop('columns')

['ID_VIVIENDA', 'ENT', 'MUN']

In [14]:
dict_grouped['data'][0]

[100002, 1, 1]

In [15]:
dict_grouped['data'][0][0]

100002

In [16]:
array_grouped = grouped.ID_VIVIENDA.unique()
array_grouped

array([ 100002,  100003,  100004, ..., 3260057, 3260058, 3260059])

In [17]:
dict_ID_VIVIENDA_ENT = {}

for line in dict_grouped['data']:
    #print(line[0], ':', line[1])
    dict_ID_VIVIENDA_ENT[line[0]] = line[1]

In [18]:
dict_ID_VIVIENDA_MUN = {}

for line in dict_grouped['data']:
    #print(line[0], ':', line[1])
    dict_ID_VIVIENDA_MUN[line[0]] = line[2]

In [19]:
df_s14['CVE_ENT'] = df_s14['ID_VIVIENDA'].map(dict_ID_VIVIENDA_ENT)

In [20]:
df_s14.CVE_ENT.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [21]:
df_s14['CVE_MUN'] = df_s14['ID_VIVIENDA'].map(dict_ID_VIVIENDA_MUN)

In [22]:
df_s14.CVE_MUN.unique()

array([  1,   5,  11,   8,   9,   4,   7,  10,   2,   3,   6,  25,  35,
        18,  30,  27,  37,  24,  32,  20,  38,  28,  33,  17,  36,  51,
       101, 106,  99,  78,  21,  19,  40,  59,  65,  75, 108,  97,  74,
       100,  80,  89, 113,  93,  61, 107,  81, 111, 102, 105,  76, 114,
       103, 112, 116,  22,  50,  45,  62,  52,  48,  29,  31,  66,  43,
        15,  14,  16,  13,  12,  23,  39,  34,  46,  42,  44,  54,  58,
        56,  55,  77,  69,  60,  57,  79,  73,  64,  49,  41,  67,  82,
        84, 118, 120,  70,  98, 124, 121, 122, 109,  92, 104,  91, 110,
       119,  95,  53,  88,  85,  68,  26, 439, 494, 531, 564, 570, 215,
       198, 307, 483, 466, 544, 508, 519, 385, 350, 399,  83, 390, 409,
       157, 375, 115, 293, 184, 546, 565, 515, 545, 525, 452, 505, 324,
       333, 340, 507, 513, 559, 554, 533, 199, 208, 207, 213, 183, 156,
       143, 152, 169, 188, 138, 140, 136, 125, 177,  71, 217, 189, 194,
       168, 202, 178, 197, 150,  47,  63, 130, 142, 204, 160, 16

In [23]:
df_s14.shape

(84629, 133)

In [24]:
df_s14.to_csv('../dataframes/delitos_2014.csv')

# 2015

## Vivienda

In [25]:
file = '../data/2015/TVivienda.csv'
df_v15 = pd.read_csv(file, encoding='latin')
df_v15['year'] = 2015
df_v15.head()

Unnamed: 0     ID_VIV     UPM  VIV_SEL  ENT  MUN  AREAM  RESUL_V  AP1_1  \
0           0  100006.01  100006        1    1    1   14.0        2      1   
1           1  100006.02  100006        2    1    1   14.0        1      1   
2           2  100006.03  100006        3    1    1   14.0        1      1   
3           3  100006.04  100006        4    1    1   14.0        1      1   
4           4  100006.05  100006        5    1    1   14.0        2      1   

   AP1_2  AP2_1  AP2_2  AP2_3  NAP2_3  FAC_VIV  EST_DIS  UPM_DIS DOMINIO  \
0      2      3      1    NaN       1      174        5        1       U   
1      2      4      1    NaN       1      174        5        1       U   
2      2      2      1    NaN       1      174        5        1       U   
3      2      2      1    NaN       1      174        5        1       U   
4      1      3      2    3.0       1      174        5        1       U   

   FAC_VIV_AM  year  
0         173  2015  
1         173  2015  
2         173  2015  
3         173  2015  
4         173  2015

In [26]:
df_v15.shape

(85729, 20)

In [27]:
df_v15['ID_VIVIENDA'] = df_v15.UPM + df_v15.VIV_SEL

## Victimización 1

In [28]:
file = '../data/2015/TPer_Vic2.csv'
df_s15 = pd.read_csv(file, encoding='latin')
df_s15['year'] = 2015
df_s15.head()

Unnamed: 0            ID_PER     UPM  VIV_SEL  HOGAR RESUL_H  R_SEL  AREAM  \
0           0  0100006.01.01.01  100006        1      1       B      1   14.0   
1           1  0100006.02.01.02  100006        2      1       A      2   14.0   
2           2  0100006.03.01.01  100006        3      1       A      1   14.0   
3           3  0100006.04.01.02  100006        4      1       A      2   14.0   
4           4  0100006.05.01.01  100006        5      1       B      1   14.0   

   AP6_1_1  AP6_1_2  ...   AP7_4_15  FAC_HOG  FAC_ELE  EST_DIS  UPM_DIS  \
0        1      1.0  ...        NaN      172      516        5        1   
1        1      1.0  ...        NaN      172      344        5        1   
2        1      1.0  ...        NaN      172      344        5        1   
3        2      NaN  ...        NaN      172      344        5        1   
4        2      NaN  ...        NaN      172      172        5        1   

   DOMINIO  ESTRATO  FAC_HOG_AM  FAC_ELE_AM  year  
0        U        3         173         519  2015  
1        U        3         173         346  2015  
2        U        3         173         346  2015  
3        U        3         173         346  2015  
4        U        3         173         173  2015  

[5 rows x 143 columns]

In [29]:
df_s15.shape

(84507, 143)

In [30]:
df_s15['ID_VIVIENDA'] = df_s15.UPM + df_s15.VIV_SEL

## DICCIONARIO Vivienda - Victimización 1

In [31]:
df_v15.groupby(['ID_VIVIENDA', 'ENT', 'MUN']).size()

ID_VIVIENDA  ENT  MUN
100007       1    1      1
100008       1    1      1
100009       1    1      2
100010       1    1      2
100011       1    1      3
100012       1    1      2
100013       1    1      2
100015       1    1      1
100019       1    1      1
100020       1    1      1
100021       1    1      1
100022       1    1      1
100023       1    1      2
100024       1    1      1
100025       1    1      1
100026       1    1      1
100027       1    1      1
100036       1    1      1
100037       1    1      1
100038       1    1      1
100039       1    1      1
100040       1    1      1
100041       1    1      1
100042       1    1      1
100043       1    1      1
100044       1    1      1
100045       1    1      1
100053       1    1      1
100054       1    1      1
100056       1    1      1
                        ..
3260748      32   55     2
3260749      32   55     2
3260750      32   55     1
3260751      32   55     2
3260752      32   55     2
326075

In [32]:
grouped = pd.DataFrame(df_v15.groupby(['ID_VIVIENDA', 'ENT', 'MUN']).size())
grouped.drop([0], axis=1, inplace=True)
grouped.head()

Empty DataFrame
Columns: []
Index: [(100007, 1, 1), (100008, 1, 1), (100009, 1, 1), (100010, 1, 1), (100011, 1, 1)]

In [33]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['ID_VIVIENDA', 'ENT', 'MUN'], dtype='object')

In [34]:
grouped.head()

ID_VIVIENDA  ENT  MUN
0       100007    1    1
1       100008    1    1
2       100009    1    1
3       100010    1    1
4       100011    1    1

In [35]:
dict_grouped = grouped.to_dict(orient='split')
dict_grouped.keys()

dict_keys(['index', 'columns', 'data'])

In [36]:
dict_grouped.pop('index')
dict_grouped.pop('columns')

['ID_VIVIENDA', 'ENT', 'MUN']

In [37]:
dict_grouped['data'][0]

[100007, 1, 1]

In [38]:
dict_grouped['data'][0][0]

100007

In [39]:
array_grouped = grouped.ID_VIVIENDA.unique()
array_grouped

array([ 100007,  100008,  100009, ..., 3260810, 3260811, 3260812])

In [40]:
dict_ID_VIVIENDA_ENT = {}

for line in dict_grouped['data']:
    #print(line[0], ':', line[1])
    dict_ID_VIVIENDA_ENT[line[0]] = line[1]

In [41]:
dict_ID_VIVIENDA_MUN = {}

for line in dict_grouped['data']:
    #print(line[0], ':', line[1])
    dict_ID_VIVIENDA_MUN[line[0]] = line[2]

In [42]:
df_s15['CVE_ENT'] = df_s15['ID_VIVIENDA'].map(dict_ID_VIVIENDA_ENT)

In [43]:
df_s15.CVE_ENT.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [44]:
df_s15['CVE_MUN'] = df_s15['ID_VIVIENDA'].map(dict_ID_VIVIENDA_MUN)

In [45]:
df_s15.CVE_MUN.unique()

array([  1,   3,   5,   6,   7,  11,   2,   4,   9,  10,   8,  18,  25,
        30,  35,  17,  20,  24,  27,  28,  32,  33,  22,  37,  38,  14,
        36,  78,  89, 101,  12,  19,  34,  40,  52,  61,  65,  74,  75,
        86,  94,  97, 106, 108,  21,  29,  31,  46,  47,  59,  81,  85,
        87,  96,  99, 102, 105, 107, 111,  15,  23,  51,  69,  76,  93,
        41,  44,  48,  54,  55,  57,  70,  92,  98, 100, 103, 109, 112,
       114, 116,  53,  45,  50,  13,  16,  39,  42,  58,  66,  43,  56,
        67,  71,  73,  77,  79,  82,  83,  84,  62,  63,  64, 120, 124,
        68, 113,  60, 104, 121, 122,  91, 110, 118,  88, 119,  49,  72,
        95,  26, 184, 385, 390, 397, 399, 515,  90, 115, 157, 185, 278,
       293, 295, 298, 324, 327, 350, 375, 384, 401, 409, 418, 441, 505,
       520, 525, 546, 551, 565, 570, 519, 198, 414, 134, 135, 142, 189,
       190, 200, 207, 208, 234, 242, 245, 254, 259, 266, 277, 309, 317,
       333, 334, 413, 422, 424, 439, 450, 453, 454, 466, 469, 49

In [46]:
df_s15.shape

(84507, 146)

In [47]:
df_s15.to_csv('../dataframes/delitos_2015.csv')

# 2016

## Vivienda

In [48]:
file = '../data/2016/tvivienda_envipe2016/conjunto_de_datos/tvivienda_envipe2016.csv'
df_v16 = pd.read_csv(file, encoding='latin')
df_v16['year'] = 2016
df_v16.head()

ID_VIV     UPM  VIV_SEL  ENT  MUN AREAM  RESULT_V  AP1_1  AP1_2  AP2_1  \
0  100006.01  100006        1    1    1  14\r         2      1      2      7   
1  100006.02  100006        2    1    1  14\r         2      1      2      2   
2  100006.03  100006        3    1    1  14\r         2      3      2      8   
3  100006.04  100006        4    1    1  14\r         1      1      2      2   
4  100006.05  100006        5    1    1  14\r         2      1      2      3   

   AP2_2 AP2_3  NAP2_3  FAC_VIV FAC_VIV_AM DOMINIO  EST_DIS  UPM_DIS  year  
0      1    \r       1      168   000168\r     U\r        2        1  2016  
1      1    \r       1      168   000168\r     U\r        2        1  2016  
2      1    \r       1      168   000168\r     U\r        2        1  2016  
3      2  02\r       2      168   000168\r     U\r        2        1  2016  
4      1    \r       1      168   000168\r     U\r        2        1  2016

In [49]:
df_v16.shape

(84140, 19)

In [50]:
df_v16['ID_VIVIENDA'] = df_v16.UPM + df_v16.VIV_SEL

## Victimización 1

In [51]:
file = '../data/2016/tper_vic2_envipe2016/conjunto_de_datos/tper_vic2_envipe2016.csv'
df_s16 = pd.read_csv(file, encoding='latin')
df_s16['year'] = 2016
df_s16.head()

ID_VIV           ID_HOG              ID_PER     UPM  VIV_SEL  HOGAR  \
0  100006.01  0100006.01.01\r  0100006.01.01.03\r  100006        1      1   
1  100006.02  0100006.02.01\r  0100006.02.01.01\r  100006        2      1   
2  100006.03  0100006.03.01\r  0100006.03.01.04\r  100006        3      1   
3  100006.04  0100006.04.01\r  0100006.04.01.01\r  100006        4      1   
4  100006.04  0100006.04.02\r  0100006.04.02.01\r  100006        4      2   

  RESUL_H  R_SEL AREAM  AP6_1_1  ...  AP7_4_15  FAC_HOG  FAC_ELE  FAC_HOG_AM  \
0     B\r      3  14\r        2  ...        \r      168      841    000168\r   
1     B\r      1  14\r        1  ...        \r      168      336    000168\r   
2     B\r      4  14\r        2  ...        \r      168      673    000168\r   
3     A\r      1  14\r        1  ...        \r      168      168    000168\r   
4     B\r      1    \r        2  ...        \r      168      168          \r   

  FAC_ELE_AM DOMINIO  ESTRATO EST_DIS UPM_DIS  year  
0   000841\r     U\r        3       2       1  2016  
1   000336\r     U\r        3       2       1  2016  
2   000673\r     U\r        3       2       1  2016  
3   000168\r     U\r        3       2       1  2016  
4         \r     U\r        3       2       1  2016  

[5 rows x 144 columns]

In [52]:
df_s16.shape

(85744, 144)

In [53]:
df_s16['ID_VIVIENDA'] = df_s16.UPM + df_s16.VIV_SEL

## DICCIONARIO Vivienda - Victimización 1

In [54]:
df_v16.groupby(['ID_VIVIENDA', 'ENT', 'MUN']).size()

ID_VIVIENDA  ENT  MUN
100007       1    1      1
100008       1    1      1
100009       1    1      2
100010       1    1      1
100011       1    1      2
100012       1    1      1
100013       1    1      2
100015       1    1      1
100023       1    1      1
100024       1    1      1
100025       1    1      1
100026       1    1      2
100027       1    1      1
100028       1    1      1
100029       1    1      1
100030       1    1      1
100032       1    1      1
100034       1    1      1
100035       1    1      1
100036       1    1      1
100041       1    1      1
100042       1    1      1
100043       1    1      1
100044       1    1      1
100045       1    1      1
100078       1    1      1
100079       1    1      1
100080       1    1      2
100081       1    1      1
100082       1    1      1
                        ..
3260796      32   37     1
3260797      32   35     1
                  37     1
3260798      32   35     1
                  37     1
326079

In [55]:
grouped = pd.DataFrame(df_v16.groupby(['ID_VIVIENDA', 'ENT', 'MUN']).size())
grouped.drop([0], axis=1, inplace=True)
grouped.head()

Empty DataFrame
Columns: []
Index: [(100007, 1, 1), (100008, 1, 1), (100009, 1, 1), (100010, 1, 1), (100011, 1, 1)]

In [56]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['ID_VIVIENDA', 'ENT', 'MUN'], dtype='object')

In [57]:
grouped.head()

ID_VIVIENDA  ENT  MUN
0       100007    1    1
1       100008    1    1
2       100009    1    1
3       100010    1    1
4       100011    1    1

In [58]:
dict_grouped = grouped.to_dict(orient='split')
dict_grouped.keys()

dict_keys(['index', 'columns', 'data'])

In [59]:
dict_grouped.pop('index')
dict_grouped.pop('columns')

['ID_VIVIENDA', 'ENT', 'MUN']

In [60]:
dict_grouped['data'][0]

[100007, 1, 1]

In [61]:
dict_grouped['data'][0][0]

100007

In [62]:
array_grouped = grouped.ID_VIVIENDA.unique()
array_grouped

array([ 100007,  100008,  100009, ..., 3260810, 3260811, 3260812])

In [63]:
dict_ID_VIVIENDA_ENT = {}

for line in dict_grouped['data']:
    #print(line[0], ':', line[1])
    dict_ID_VIVIENDA_ENT[line[0]] = line[1]

In [64]:
dict_ID_VIVIENDA_MUN = {}

for line in dict_grouped['data']:
    #print(line[0], ':', line[1])
    dict_ID_VIVIENDA_MUN[line[0]] = line[2]

In [65]:
df_s16['CVE_ENT'] = df_s16['ID_VIVIENDA'].map(dict_ID_VIVIENDA_ENT)

In [66]:
df_s16.CVE_ENT.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [67]:
df_s16['CVE_MUN'] = df_s16['ID_VIVIENDA'].map(dict_ID_VIVIENDA_MUN)

In [68]:
df_s16.CVE_MUN.unique()

array([  1,   5,   6,   7,  11,   2,   9,  10,   4,   3,   8,  18,  25,
        30,  35,  17,  20,  24,  27,  28,  31,  32,  33,  22,  37,  36,
        13,  26,  78,  89, 101,  12,  19,  34,  40,  51,  52,  61,  65,
        74,  75,  86,  94, 106, 108,  29,  41,  46,  47,  59,  66,  71,
        79,  81,  85,  87,  96,  99, 102, 105, 107, 111, 114,  15,  23,
        62,  76,  93,  97,  14,  21,  48,  49,  55,  57,  67,  70,  80,
        82,  83,  92,  98, 103, 109, 112, 116,  50,  60,  16,  38,  39,
        42,  44,  58,  43,  68,  54,  45,  53,  64,  72,  77,  56,  69,
        84,  63,  73, 120, 119, 121, 124, 117, 104, 122,  91, 110, 118,
       100, 113,  88, 184, 385, 390, 397, 399, 413, 482,  90, 131, 157,
       185, 188, 197, 198, 248, 293, 295, 298, 324, 327, 375, 384, 401,
       409, 441, 467, 505, 515, 520, 546, 551, 553, 403, 130, 134, 135,
       161, 166, 189, 190, 200, 207, 208, 242, 253, 277, 278, 309, 317,
       333, 334, 378, 414, 424, 439, 454, 466, 469, 492, 513, 52

In [69]:
df_s16.shape

(85744, 147)

In [70]:
df_s16.to_csv('../dataframes/delitos_2016.csv')

# 2017

## Vivienda

In [71]:
file = '../data/2017/tvivienda_envipe2017/conjunto_de_datos/tvivienda.csv'
df_v17 = pd.read_csv(file, encoding='latin')
df_v17['year'] = 2017
df_v17.head()

ID_VIV     UPM  VIV_SEL AREAM  CVE_ENT           NOM_ENT  CVE_MUN  \
0  100008.01  100008        1  14\r        1  Aguascalientes\r        1   
1  100008.02  100008        2  14\r        1  Aguascalientes\r        1   
2  100008.04  100008        4  14\r        1  Aguascalientes\r        1   
3  100008.05  100008        5  14\r        1  Aguascalientes\r        1   
4  100022.01  100022        1  14\r        1  Aguascalientes\r        1   

            NOM_MUN  RESULT_V  AP1_1  ...   AP2_1  AP2_2  AP2_3 NAP2_3  \
0  Aguascalientes\r         2      1  ...       4      1     \r      1   
1  Aguascalientes\r         2      1  ...       3      1     \r      1   
2  Aguascalientes\r         2      1  ...       2      1     \r      1   
3  Aguascalientes\r         1      2  ...       3      1     \r      1   
4  Aguascalientes\r         1      1  ...       3      1     \r      1   

   FAC_VIV  FAC_VIV_AM DOMINIO EST_DIS  UPM_DIS  year  
0      204    000204\r     U\r       3        1  2017  
1      204    000204\r     U\r       3        1  2017  
2      204    000204\r     U\r       3        1  2017  
3      204    000204\r     U\r       3        1  2017  
4      198    000198\r     U\r       2        2  2017  

[5 rows x 21 columns]

In [72]:
df_v17.shape

(90618, 21)

In [73]:
df_v17['ID_VIVIENDA'] = df_v17.UPM + df_v17.VIV_SEL

## Victimización 1

In [74]:
file = '../data/2017/tper_vic2_envipe2017/conjunto_de_datos/tper_vic2.csv'
df_s17 = pd.read_csv(file, encoding='latin')
df_s17['year'] = 2017
df_s17.head()

ID_VIV           ID_HOG              ID_PER     UPM  VIV_SEL  HOGAR  \
0  100008.01  0100008.01.01\r  0100008.01.01.01\r  100008        1      1   
1  100008.02  0100008.02.01\r  0100008.02.01.02\r  100008        2      1   
2  100008.04  0100008.04.01\r  0100008.04.01.01\r  100008        4      1   
3  100008.05  0100008.05.01\r  0100008.05.01.01\r  100008        5      1   
4  100022.01  0100022.01.01\r  0100022.01.01.03\r  100022        1      1   

  RESUL_H  R_SEL  SEXO  EDAD  ...  AP7_4_15  FAC_HOG FAC_ELE  FAC_HOG_AM  \
0     B\r      1     1    40  ...        \r      204     408    000204\r   
1     B\r      2     2    70  ...        \r      204     611    000204\r   
2     B\r      1     1    85  ...        \r      204     408    000204\r   
3     A\r      1     1    28  ...        \r      204     408    000204\r   
4     A\r      3     1    22  ...        \r      198     595    000198\r   

  FAC_ELE_AM  DOMINIO ESTRATO  EST_DIS  UPM_DIS  year  
0   000408\r      U\r       4        3        1  2017  
1   000611\r      U\r       4        3        1  2017  
2   000408\r      U\r       4        3        1  2017  
3   000408\r      U\r       4        3        1  2017  
4   000595\r      U\r       3        2        2  2017  

[5 rows x 150 columns]

In [75]:
df_s17.shape

(92551, 150)

In [76]:
df_s17['ID_VIVIENDA'] = df_s17.UPM + df_s17.VIV_SEL

## DICCIONARIO Vivienda - Victimización 1

In [77]:
df_v17.groupby(['ID_VIVIENDA', 'CVE_ENT', 'CVE_MUN']).size()

ID_VIVIENDA  CVE_ENT  CVE_MUN
100009       1        1          1
100010       1        1          1
100012       1        1          1
100013       1        1          1
100023       1        1          1
100024       1        1          1
100025       1        1          1
100027       1        1          1
100060       1        1          1
100061       1        1          1
100062       1        1          1
100063       1        1          1
100064       1        1          1
100080       1        1          1
100081       1        1          1
100082       1        1          1
100084       1        1          1
100091       1        1          1
100092       1        1          1
100093       1        1          1
100094       1        1          1
100095       1        1          1
100102       1        1          1
100103       1        1          1
100104       1        1          2
100106       1        1          3
100107       1        1          2
100108       1        1  

In [78]:
grouped = pd.DataFrame(df_v17.groupby(['ID_VIVIENDA', 'CVE_ENT', 'CVE_MUN']).size())
grouped.drop([0], axis=1, inplace=True)
grouped.head()

Empty DataFrame
Columns: []
Index: [(100009, 1, 1), (100010, 1, 1), (100012, 1, 1), (100013, 1, 1), (100023, 1, 1)]

In [79]:
grouped.reset_index(inplace=True)
grouped.columns

Index(['ID_VIVIENDA', 'CVE_ENT', 'CVE_MUN'], dtype='object')

In [80]:
grouped.head()

ID_VIVIENDA  CVE_ENT  CVE_MUN
0       100009        1        1
1       100010        1        1
2       100012        1        1
3       100013        1        1
4       100023        1        1

In [81]:
dict_grouped = grouped.to_dict(orient='split')
dict_grouped.keys()

dict_keys(['index', 'columns', 'data'])

In [82]:
dict_grouped.pop('index')
dict_grouped.pop('columns')

['ID_VIVIENDA', 'CVE_ENT', 'CVE_MUN']

In [83]:
dict_grouped['data'][0]

[100009, 1, 1]

In [84]:
dict_grouped['data'][0][0]

100009

In [85]:
array_grouped = grouped.ID_VIVIENDA.unique()
array_grouped

array([ 100009,  100010,  100012, ..., 3260819, 3260820, 3260821])

In [86]:
dict_ID_VIVIENDA_ENT = {}

for line in dict_grouped['data']:
    #print(line[0], ':', line[1])
    dict_ID_VIVIENDA_ENT[line[0]] = line[1]

In [87]:
dict_ID_VIVIENDA_MUN = {}

for line in dict_grouped['data']:
    #print(line[0], ':', line[1])
    dict_ID_VIVIENDA_MUN[line[0]] = line[2]

In [88]:
df_s17['CVE_ENT'] = df_s17['ID_VIVIENDA'].map(dict_ID_VIVIENDA_ENT)

In [89]:
df_s17.CVE_ENT.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [90]:
df_s17['CVE_MUN'] = df_s17['ID_VIVIENDA'].map(dict_ID_VIVIENDA_MUN)

In [91]:
df_s17.CVE_MUN.unique()

array([  1,   2,  11,   9,   3,   4,   5,   6,   7,  10,   8,  18,  25,
        30,  35,  17,  20,  24,  27,  28,  31,  32,  33,  22,  23,  38,
        37,  78,  89,  93,  96, 101,  15,  19,  40,  52,  57,  59,  61,
        65,  69,  74,  76,  86,  75, 106, 108, 109,  13,  21,  29,  34,
        46,  47,  68,  66,  71,  79,  81,  83,  85,  87,  99, 102, 103,
       105, 107, 111, 112,  97,  41,  48,  49,  51,  55,  67,  80,  82,
        92,  94, 114, 115,  53,  36,  45,  50,  12,  54,  14,  16,  39,
        42,  56,  73,  62,  64,  72,  77,  63,  58,  70,  26,  44,  60,
        84,  98, 120, 125, 119, 121, 100, 124, 104, 122,  43,  91, 110,
       118, 113,  88,  95, 184, 134, 385, 390, 397, 399, 413, 482, 515,
       525, 526, 131, 150, 141, 153, 157, 188, 185, 198, 201, 227, 248,
       293, 295, 324, 350, 367, 375, 401, 398, 409, 418, 441, 469, 472,
       475, 551, 553, 557, 167, 190, 207, 225, 234, 253, 278, 310, 309,
       318, 334, 344, 364, 378, 406, 446, 439, 459, 454, 491, 55

In [92]:
df_s17.shape

(92551, 151)

In [93]:
df_s17.to_csv('../dataframes/delitos_2017.csv')